repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2
name: Gleb Grishakov
title: Ruby Developer
email: glebflow@proton.me
website: http://glebsoti.beget.tech/
darkmode: false
github_username:  glebson1988
linkedin_username: glebflow
#additional_links:
#- title: Habr
#  icon: fa fa-code
#  url: https://career.habr.com/glebson1988
about_profile_image: images/profile.jpg
about_content: |
  <mark>Fullstack Developer | Ruby on Rails Specialist</mark>

  Experienced Fullstack Developer with a strong focus on <mark>Ruby on Rails</mark>, <mark>PostgreSQL/MySQL</mark>, <mark>Docker</mark>, and cloud services (<mark>AWS</mark>, <mark>Heroku</mark>). Proven track record across diverse domains: billing systems, SaaS platforms, educational and healthcare apps.

  **Key Projects & Responsibilities:**

  **Billing platform** – implemented complex service cost calculations, invoicing, document workflows (<mark>RoR</mark>, <mark>MySQL</mark>, <mark>Sidekiq</mark>, <mark>Redis</mark>).

  **CV builder SaaS** – built features for company/project knowledge base, handled deployment (<mark>RoR</mark>, <mark>Heroku</mark>).

  **Mental health app (Wriite)** – led development team, conducted code reviews (<mark>RoR</mark>, <mark>React</mark>, <mark>RSpec</mark>).

  **Kids' competition app (Melobeem)** – built backend API, CI/CD, Stripe payments, Facebook API integration (<mark>RoR</mark>, <mark>AWS</mark>, <mark>Docker</mark>).

  **Dental CMS (Viviosites)** – fullstack dev, templating system extensions (<mark>RoR 3</mark>, <mark>jQuery</mark>).

  **Landlord portal (Helpthemove)** – added reporting tools, new features (<mark>RoR</mark>, <mark>dry-monads</mark>, <mark>Sidekiq</mark>).

  **Optometry management (Floe)** – HIPAA-compliant features, office/sales integration (<mark>RoR</mark>, <mark>GitLab</mark>, <mark>Docker</mark>).

  Strong in test-driven development (<mark>RSpec</mark>), API design, CI/CD, team collaboration, and mentoring.
content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Billing
        quote: >
          December 2021 - present.
        description: |
          A service that implements everything related the calculating the cost of services, invoicing, working with related docs, etc.

          Role: <mark>Fullstack Developer</mark>.

          Responsibilities: New features.

          Environment: <mark>Ruby, Rails, RSpec, MySQL, Docker, Slack API, Sidekiq, Redis</mark>.
      - layout: top-middle
        title: Team
        quote: >
          Aug 2021 - Dec 2021
        description: |
          Web app that is used to create CV and store information about employees, up-to-date information about company and projects.

          Role: <mark>Fullstack Developer</mark>.

          Responsibilities: New features, code review, deploy.

          Environment: <mark>Ruby, Rails, RSpec, PostgreSQL, Heroku</mark>.
      - layout: top-middle
        title: Wriite
        quote: >
          Aug 2021 - Oct 2021
        description: |
          Guided writing and practices that help to reduce anxiety, relieve depression and overcome the effects of lockdown.

          Role: <mark>Team lead</mark>.

          Responsibilities: Team leading, code review.

          Environment: <mark>Ruby, Rails, RSpec, React, Heroku</mark>.
      - layout: top-middle
        title: Melobeem
        quote: >
          Jan 2021 - Aug 2021
        description: |
          Kids competition app. You vote for cute kids, buy votes, spins etc. And at the end of monthly competition take your prize!

          Role: <mark>Backend developer</mark>.

          Responsibilities: Rails API, dockerising app for development, adding Github CI. Also working with AWS (ECR, EC2, RDS etc). Adding Stripe payment system. Sidekiq scheduled jobs.

          Environment: <mark>Ruby, Rails, RSpec, Redis, Amazon: EC2, ECS, RDS; Docker, GitHub Actions, Facebook API, Stripe, Sidekiq</mark>.
      - layout: top-middle
        title: Viviosites
        quote: >
          Jun 2021 - Jul 2021
        description: |
          Dental website CMS.

          Role: <mark>Fullstack developer</mark>.

          Responsibilities: Adding new themes for the template engine, written on RoR 3rd version!

          Environment: <mark>Ruby, Rails, Docker, jQuery</mark>.
      - layout: top-middle
        title: Helpthemove
        quote: >
          Nov 2020 - Jun 2021
        description: |
          Portal for landlords facilitating the transfer of meter readings.

          Role: <mark>Fullstack developer</mark>.

          Responsibilities: New features, also integration new web tool for report generation.

          Environment: <mark>Ruby, Rails, Bootstrap, jQuery, Sidekiq, Postgres, dry-struct, dry-monads, Heroku</mark>.
      - layout: top-middle
        title: Floe Optometry
        quote: >
          Jul 2020 - Oct 2020
        description: |
          App for the optometry practice. It provides office management tools and sales integration with the optics distributor.

          Role: <mark>Fullstack developer</mark>.

          Responsibilities: New features and fixing bugs.

          Environment: <mark>Ruby, Rails, Sidekiq, Postgres, Gitlab, Docker, HIPAA Compliance</mark>.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Flant
        link: flant.com
        sub_title: Ruby developer
        caption: December 2021 - Present
        quote: >
          Fullstack developer in the Billing project.
        description: |
            Big application for all: costing clients, all kinds of reports, sending data to various APIs, Slack notification system etc.
      - layout: left
        title: Cybergizer
        link: cybergizer.com
        sub_title: Ruby developer
        caption: July 2020 - November 2021
        quote: >
          Participating in several projects in different roles: <mark>backend developer, fullstack developer, team lead</mark>.
        description: |
          Applications:  <mark>Team, Melobeem, Viviosites, Wriite, Helpthemove, Optometry</mark>. More details about each project a little higher.
  - title: Education
    layout: list
    content:
      - layout: left
        title: Saint Petersburg State University of Aerospace Instrumentation
        caption: 2005 - 2010
        sub_title: Innovative Technologies in Electromechanics and Energy
        quote: >
          The Saint Petersburg State University of Aerospace Instrumentation is a university with 13 faculties in Saint Petersburg, Russia. Faculties are devoted to innovation management, aerospace engineering, electronic engineering, energy development, computer science, telecommunication, humanities, military science, economics, jurisprudence and special faculties for distance education and recently acquired colleges.
        description: |
          During university time I learnt most of my key skills that I have taken through my career such as working to tight deadlines. I thoroughly enjoyed my time at the university and learnt a lot about a healthy work life balance.
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
 - jekyll-seo-tag
